/** 
* @AutoGeneratedFunctions Indicates that this is auto generated function through screen editor. Modifying this tag or the script may lead to inconsistent views in screen editor events.
*/
export function Screen1_HmiButton_1_Down() {
    //Tag.Write(ServerInterfaces_Server_Interface_1_tank_inputValve_isEmergencyDraining, True);
    Tags("ServerInterfaces_Server_Interface_1_tank_outputValve_isEmergencyDraining").Write(true);
}
/** 
* @AutoGeneratedFunctions Indicates that this is auto generated function through screen editor. Modifying this tag or the script may lead to inconsistent views in screen editor events.
*/
export function Screen1_HmiButton_1_KeyUp() {
    Tag.Write(undefined,undefined);
}